version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  release-watcher:
    lang: golang-middleware-inproc
    handler: ./release-watcher
    image: ${SERVER:-ttl.sh}/${OWNER:-openfaas}/release-watcher:${TAG:-latest}
    annotations:
      topic: cron-function
      schedule: ${CRON_SCHEDULE:-0 */8 * * *}
    environment:
      watch_repo: ${WATCH_REPO:-openfaas/faas}
      postgres_host: ${POSTGRES_HOST:-postgresql}
      postgres_port: ${POSTGRES_PORT:-5432}
      postgres_user: ${POSTGRES_USER:-postgres}
      postgres_db: ${POSTGRES_DB:-postgres}
    secrets:
      - releases-discord-webhook-url
      - postgres-passwd

configuration:
  templates:
    - name: golang-middleware-inproc
      source: https://github.com/openfaas/golang-http-template